### ISSUE TITLE
Can 2080Ti GPU support the computation power?

### ISSUE THREAD

**Issue by momo1986** [dongyp13/Adversarial-Distributional-Training#2]
Just for confirm, I try to run default adt_expam algorithm on a leasehold server, however, the connection is closed. I want to know whether it is the problem of server itself or whether the single-GPU of 2080Ti cannot support the batch-size of GPU memory on the default setting.

Moreover, thanks for you sharing and contribution.

Regards!
Momo

**Comment by dongyp13** [comment]
A single 2080Ti is sufficient to run the experiments. We also ran our experiments on 2080Ti.
